### ISSUE TITLE
Request for Additional Experimental Details

### ISSUE THREAD

**Issue by QUEAHREN** [wyang-vis/EIFNet#4]
While I have followed the methodology and settings as described, there seems to be a significant discrepancy between my results and the ones you have published. To ensure that I am not missing any critical steps or parameters, I would greatly appreciate it if you could provide additional details。

**Comment by wyang-vis** [comment]
If so could you show the results below and also what additional details you would like to know.

**Comment by QUEAHREN** [comment]
Okay, here are the details of my experimental setup, based on the BasicSR framework: 

```
num_gpu:  1 #4

datasets:
  train:
    crop_size: 256
    use_flip: true
    use_rot: true
    batch_size_per_gpu: 8 # 4 for 2080, 8 for titan
  val:
    crop_size: ~
    use_flip: false
    use_rot: false

dataset_name: GoPro

# network structures
network_g:
  type: EIFNet

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 200000 
    eta_min: !!float 1e-6

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
```
At the same time, I have tried different iterations, but the results are not good.  It should be noted that the Raw event stream I used is downloaded from EFNet, but I have rewritten my dataset files when training EIFNet according to your representation division method in your dataset files. Despite this, I still cannot achieve the results in your paper.
